version: '3'
services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: fvtt
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /home/user/foundrydata:/data/foundryvtt
      - /home/user/foundrydl:/host
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.middlewares.foundryvtt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.foundryvtt-secure.entrypoints=https"
      - "traefik.http.routers.foundryvtt-secure.rule=Host(`play.yourdomain.com`)"
      - "traefik.http.routers.foundryvtt-secure.service=foundryvtt"
      - "traefik.http.routers.foundryvtt-secure.tls=true"
      - "traefik.http.routers.foundryvtt-secure.tls.certresolver=http"
      - "traefik.http.routers.foundryvtt.entrypoints=http"
      - "traefik.http.routers.foundryvtt.middlewares=foundryvtt-https-redirect"
      - "traefik.http.routers.foundryvtt.rule=Host(`play.yourdomain.com`)"
      - "traefik.http.services.foundryvtt.loadbalancer.server.port=30000"

networks:
  proxy:
    external: true

