version: '3'
services:
  foundryvtt-§§USER§§:
    image: direckthit/fvtt-docker:latest
    container_name: §§USER§§-fvtt
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /home/§§USER§§/foundrydata:/data/foundryvtt
      - /home/§§USER§§/foundrydl:/host
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.middlewares.§§USER§§foundryvtt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.§§USER§§foundryvtt-secure.entrypoints=https"
      - "traefik.http.routers.§§USER§§foundryvtt-secure.rule=Host(`§§GAMEURL§§`)"
      - "traefik.http.routers.§§USER§§foundryvtt-secure.service=§§USER§§foundryvtt"
      - "traefik.http.routers.§§USER§§foundryvtt-secure.tls=true"
      - "traefik.http.routers.§§USER§§foundryvtt-secure.tls.certresolver=http"
      - "traefik.http.routers.§§USER§§foundryvtt.entrypoints=http"
      - "traefik.http.routers.§§USER§§foundryvtt.middlewares=§§USER§§foundryvtt-https-redirect"
      - "traefik.http.routers.§§USER§§foundryvtt.rule=Host(`§§GAMEURL§§`)"
      - "traefik.http.services.§§USER§§foundryvtt.loadbalancer.server.port=§§PORT§§"

networks:
  proxy:
    external: true

